GT.Application/Models/Catalogos/CategoriaModel.cs
using GT.Application.ServiceCatalogos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Web;

namespace GT.Application.Models.Catalogos
{

    public class CategoriaModel
    {
        private string bindigDifusion = "BasicHttpBinding_IServiceCatalogos";


        public VMCat_Categoria RegistrarCategoria(VMCat_Categoria modelo)
        {
            try
            {
                ServiceCatalogosClient cliente = new ServiceCatalogosClient(bindigDifusion);
                VMCat_Categoria resp = cliente.RegistrarCategoria(modelo);
                cliente.Close();
                return resp;
            }
            catch (FaultException<ExceptionService> ex)
            {
                throw new Exception(ex.Detail.Mensaje);
            }
        }

        public VMCat_Categoria ObtenerCategoria(short id)
        {
            try
            {
                ServiceCatalogosClient cliente = new ServiceCatalogosClient(bindigDifusion);

                VMCat_Categoria resp = cliente.ObtenerInfoCategoria(id);
                cliente.Close();
                return resp;
            }
            catch (FaultException<ExceptionService> ex)
            {
                throw new Exception(ex.Detail.Mensaje);
            }
        }

        public void EditarCategoria(VMCat_Categoria modelo)
        {
            try
            {
                ServiceCatalogosClient cliente = new ServiceCatalogosClient(bindigDifusion);

                cliente.EditarCategoria(modelo);
                cliente.Close();
            }
            catch (FaultException<ExceptionService> ex)
            {
                throw new Exception(ex.Detail.Mensaje);
            }
        }

        public VMCat_Categoria[] ListarCategorias(bool todos)
        {
            try
            {
                ServiceCatalogosClient cliente = new ServiceCatalogosClient(bindigDifusion);
                VMCat_Categoria[] resp = cliente.ListarCategorias(todos);
                cliente.Close();
                return resp;
            }
            catch (FaultException<ExceptionService> ex)
            {
                throw new Exception(ex.Detail.Mensaje);
            }
        }

        public void BajaCategoria(short id)
        {
            try
            {
                ServiceCatalogosClient cliente = new ServiceCatalogosClient(bindigDifusion);
                cliente.BajaCategoria(id);
                cliente.Close();
            }
            catch (FaultException<ExceptionService> ex)
            {
                throw new Exception(ex.Detail.Mensaje);
            }
        }
    }
}

GT.Application/Controllers/Catalogos/CategoriaController.cs
using GT.Application.Filters;
using GT.Application.Models.Catalogos;
using GT.Application.ServiceCatalogos;
using GT.Application.VM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GT.Application.Controllers.Catalogos
{
    public class CategoriaController : Controller
    {
        CategoriaModel moduloModel = new CategoriaModel();

        // GET: Categoria
        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public JsonResult Registrar(VMCat_Categoria model)
        {
            RespuestaModel resp = new RespuestaModel();
            try
            {
                resp.result = moduloModel.RegistrarCategoria(model);
                resp.success = true;
                resp.alerta = "Categoria registrada correctamente";
            }
            catch (Exception ex)
            {
                resp.success = false;
                resp.mensaje = ex.Message;
            }

            return Json(new { model = resp }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult ObtenerInfo(short id)
        {
            VMCat_Categoria model = moduloModel.ObtenerCategoria(id);
            return Json(new { model }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Editar(VMCat_Categoria model)
        {
            RespuestaModel resp = new RespuestaModel();
            try
            {

                moduloModel.EditarCategoria(model);
                resp.result = model;
                resp.success = true;
                resp.alerta = "Información actualizada correctamente";

            }
            catch (Exception ex)
            {
                resp.success = false;
                resp.mensaje = ex.Message;
            }


            return Json(new { model = resp }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Baja(short id)
        {
            RespuestaModel resp = new RespuestaModel();
            try
            {

                moduloModel.BajaCategoria(id);
                resp.success = true;
                resp.alerta = "Información actualizada correctamente";

            }
            catch (Exception ex)
            {
                resp.success = false;
                resp.mensaje = ex.Message;
            }


            return Json(new { model = resp }, JsonRequestBehavior.AllowGet);
        }

        [SessionTimeoutActionFilter]
        [HttpPost]
        public JsonResult Listar(bool todos = true)
        {
            RespuestaModel resp = new RespuestaModel();
            try
            {
                resp.result = moduloModel.ListarCategorias(todos);
                resp.success = true;
            }
            catch (Exception ex)
            {
                resp.success = false;
                resp.mensaje = ex.Message;
            }

            return Json(new { model = resp }, JsonRequestBehavior.AllowGet);
        }

    }
}

GT.Application/Controllers/Conceptos/ConceptoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GT.Application.Controllers.Conceptos
{
    public class ConceptoController : Controller
    {
        // GET: Concepto
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SearchResult()
        {
            return View();
        }
    }
}

GT.Application/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GT.Application.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

GT.Application/Views/Categoria/Index.cshtml
@{
    ViewBag.Title = "Categorias";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section styles
{

}
@section title
{
    <h2>@ViewBag.Title</h2>
}
@section breadcrumb
{
    <div class="right-wrapper pull-right">
        <ol class="breadcrumbs">
            <li>
                <a href='@Url.Action("Index", "Home")'>
                    <i class="fa fa-home"></i>
                </a>
            </li>
            <li><span>Catalogos</span></li>
            <li><span>@ViewBag.Title</span></li>
            <li></li>
        </ol>
    </div>
}
<section id="container" class="panel">
    <header class="panel-heading">
        <div class="panel-actions">
            <a href="#" class="fa fa-caret-down"></a>
            <a href="#" class="fa fa-times"></a>
        </div>

        <h2 class="panel-title">@ViewBag.Title</h2>


    </header>
    <div class="panel-body">
        <div class="alert" v-bind:class="errorRegistroCategoria.css" v-if="(errorRegistroCategoria.msg.length > 0)">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <strong>Alerta!</strong> {{errorRegistroCategoria.msg}}
        </div>
        <button type="button" class="mb-xs mt-xs mr-xs btn btn-primary" data-toggle="modal" data-target="#modalAddEdit" v-on:click="limpiarFormRegistro(); isEdit=false;"><i class="fa fa-plus"></i> Nuevo</button>

        <table class="table table-bordered table-striped mb-none" id="datatable">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th>Descripción</th>
                    <th>Activo</th>
                    <th>Acciones</th>
                </tr>
            </thead>

            <tbody>
                <template id="row" functional>
                    <tr class="gradeA" v-for="row in listCategorias">
                        <td>{{row.FiId}}</td>
                        <td style="width:20%">{{row.FcNombre}}</td>
                        <td style="width:50%">{{row.FcDescripcion}}</td>
                        <td class="center">
                            <div class="checkbox-custom checkbox-default">
                                <input type="checkbox" v-bind:checked="row.FlActivo" disabled="" id="chkActivo">
                                <label for="chkActivo"></label>
                            </div>
                        </td>
                        <td class="center">
                            <a href="#" class="on-default edit-row"  v-on:click="openEdit(row.FiId)" data-toggle="modal" data-target="#modalAddEdit"><i class="fa fa-pencil"></i></a>
                            <a href="#" class="on-default remove-row"><i class="fa fa-trash-o" v-on:click="bajaCategoria(row.FiId)"></i></a>
                        </td>
                    </tr>
                </template>
            </tbody>
        </table>
    </div>

    <!-- Modal -->


    <div class="modal fade" id="modalAddEdit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="myModalLabel">{{ !isEdit ? 'NUEVO': 'EDITAR' }}</h4>
                </div>
                <div class="modal-body">
                    <form id="demo-form" class="form-horizontal mb-lg" novalidate="novalidate">
                        <div class="form-group mt-lg">
                            <label class="col-sm-3 control-label">Id</label>
                            <div class="col-sm-9">
                                <input type="text" name="id" class="form-control" v-model="modelCategoria.FiId" disabled="" placeholder="Id" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Nombre</label>
                            <div class="col-sm-9">
                                <input type="text" name="nombre" class="form-control" v-model="modelCategoria.FcNombre" placeholder="Nombre" required />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Descripcion</label>
                            <div class="col-sm-9">
                                <textarea rows="5" class="form-control" placeholder="Descripción" v-model="modelCategoria.FcDescripcion"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-9">
                                <div class="checkbox-custom checkbox-default">
                                    <input type="checkbox" v-model="modelCategoria.FlActivo" v-bind:disabled="!isEdit" id="chkActivoNE">
                                    <label for="chkActivoNE">Activo</label>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-success" v-on:click="registrarEditarCategoria" v-if="formCategoriaCompleto">{{ !isEdit ? 'GUARDAR': 'ACTUALIZAR' }}</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">CERRAR</button>
                </div>
            </div>
        </div>
    </div>
</section>


@section scripts
{

    @*<script src="~/Content/js/tables/examples.datatables.default.js"></script>*@
    <script src="~/ViewScripts/Catalogos/categoria-1.0.0.js"></script>
}

GT.Application/Views/Concepto/Index.cshtml
@{
    ViewBag.Title = "Conceptos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section styles
{
    @Styles.Render("~/Content/forms")
    @Styles.Render("~/Content/codemirror")
}
@section title
{
    <h2>@ViewBag.Title</h2>
}
@section breadcrumb
{
    <div class="right-wrapper pull-right">
        <ol class="breadcrumbs">
            <li>
                <a href='@Url.Action("Index", "Home")'>
                    <i class="fa fa-home"></i>
                </a>
            </li>
            <li><span>Terminos</span></li>
            <li><span>@ViewBag.Title</span></li>
            <li></li>
        </ol>
    </div>
}

<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                <div class="panel-actions">
                    <a href="#" class="fa fa-caret-down"></a>
                    <a href="#" class="fa fa-times"></a>
                </div>

                <h2 class="panel-title">Nuevo Concepto</h2>
            </header>
            <div class="panel-body">
                <form class="form-horizontal form-bordered" method="get">
                    <div class="form-group">
                        <label class="col-md-3 control-label" for="inputNombre">Nombre</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" id="inputNombre">
                        </div>
                    </div>



                    <div class="form-group">
                        <label class="col-md-3 control-label" for="inputDescripcion">Descripción</label>
                        <div class="col-md-6">
                            <textarea class="form-control" id="inputDescripcion"></textarea>
                            <span class="help-block">Descripción general del termino o concepto.</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Categoría</label>
                        <div class="col-md-6">
                            <select class="form-control" multiple="multiple" data-plugin-multiselect id="ms_example2">
                                <option value="1" selected>Categoria 1 </option>
                                <option value="2" selected>Categoria 2 </option>
                                <option value="3" selected>Categoria 3 </option>
                                <option value="4">Categoria 4 </option>
                                <option value="5">Categoria 5 </option>
                                <option value="6">Categoria 6 </option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="tags-input" class="col-md-3 control-label">Tags</label>
                        <div class="col-md-6">
                            <input name="tags" id="tags-input" data-role="tagsinput" data-tag-class="label label-primary" class="form-control" value="Tag 1,Tag 2,Tag 3,Tag 4,Tag 5" />
                            <p>
                                Añada las etiquetas con las que quiere reconocer este concepto
                            </p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="textareaEditor">SQL Code</label>
                        <div class="col-md-6">
                            <textarea class="form-control" rows="10" id="codemirror_js_code" name="code_js" data-plugin-codemirror data-plugin-options='{ "mode": "text/x-plsql" }'>
SELECT * FROM 
</textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="textareaEditor">Archivos</label>
                        <div class="col-md-6">
                            <div action="/upload" class="dropzone dz-square" id="dropzone-example"></div>
                        </div>
                    </div>

                </form>
            </div>
            <div class="panel-footer">
                <div class="right">
                    <button class="btn btn-success btn-lg"> GUARDAR</button>
                    <button class="btn btn-default btn-lg"> CANCELAR</button>
                </div>
                
            </div>
        </section>


    </div>
</div>

@section scripts
{

    @Scripts.Render("~/bundles/forms")
    @Scripts.Render("~/bundles/codemirror")
}

GT.Application/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section title
{
    <h2>@ViewBag.Title</h2>
}
@section breadcrumb
{
    <div class="right-wrapper pull-right">
        <ol class="breadcrumbs">
            <li>
                <a href='@Url.Action("Index", "Home")'>
                    <i class="fa fa-home"></i>
                </a>
            </li>
            <li><span>Home</span></li>
            <li><span>@ViewBag.Title</span></li>
            <li></li>
        </ol>
    </div>
}



<!-- start: page -->
<h3 class="mt-none">TÉRMINOS APS/PDW</h3>
<p>Buscar definiciones, buenas practica y recomendaciones en el uso del APS/PDW</p>
<div class="search-control-wrapper">
    <form action="pages-search-results.html">
        <div class="form-group">
            <div class="input-group">
                <input type="text" class="form-control input-lg" placeholder="e.g. index, tablas, temporales">
                <span class="input-group-btn">
                    <a class="btn btn-primary btn-lg" href="@Url.Action("SearchResult", "Concepto")">
                       BUSCAR
                    </a>
                </span>
            </div>
        </div>
    </form>
</div>
<div class="row">
    <div class="col-md-8 col-lg-8 col-xl-12">
        <h5 class="text-semibold text-dark text-uppercase mb-md mt-lg">CATEGORIAS</h5>
        <section class="panel">

            <div class="panel-body">
                <p class="m-none">
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-default">Indices</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-default">Cargas/Backups</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-default">Querys</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-default">Performance</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-default">Categoria 1</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-default">Categoria 2</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-default">Categoria 3</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-default">Categoria 4</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-default">Categoria 5</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-default">Categoria 6</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-default">Categoria 7</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-default">Categoria 8</button>
                </p>
            </div>
        </section>

        <h5 class="text-semibold text-dark text-uppercase mb-md mt-lg">ALFABETICAMENTE</h5>
        <section class="panel">

            <div class="panel-body">
                <p class="m-none">
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">A</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">B</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">C</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">D</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">E</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">F</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">G</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">H</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">I</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">J</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">K</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">L</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">M</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">N</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">Ñ</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">O</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">P</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">Q</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">R</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">S</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">T</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">U</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">V</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">W</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">X</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">Y</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-lg btn-primary">Z</button>
                </p>
            </div>
        </section>
    </div>
    <div class="col-md-4 col-lg-4 col-xl-12">
        <h5 class="text-semibold text-dark text-uppercase mb-md mt-lg">ULTIMOS TERMINOS AÑADIDOS</h5>
        <section class="panel">
            <header class="panel-heading">
                <div class="panel-actions">
                    <a href="#" class="fa fa-caret-down"></a>
                    <a href="#" class="fa fa-times"></a>
                </div>

                <h2 class="panel-title">TÉRMINOS</h2>
            </header>
            <div class="panel-body">
                <div class="sidebar-widget widget-tasks">
                    <div class="widget-content">
                        <ul class="list-unstyled m-none">
                            <li><a href="#">Querys</a></li>
                            <li><a href="#">ETLs</a></li>
                            <li><a href="#">Categoria X</a></li>
                            <li><a href="#">Categoria Y</a></li>
                            <li><a href="#">Categoria Z</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>
        <section class="panel">
            <header class="panel-heading">
                <div class="panel-actions">
                    <a href="#" class="fa fa-caret-down"></a>
                    <a href="#" class="fa fa-times"></a>
                </div>

                <h2 class="panel-title">TAGS</h2>
            </header>
            <div class="panel-body">
                <p class="m-none">
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-sm btn-warning">tag one</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-sm btn-success">tag one</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-sm btn-primary">tag one</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-sm btn-default">tag one</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-sm btn-danger">tag one</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-sm btn-dark">tag one</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-sm btn-warning">tag one</button>
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-sm btn-success">tag one</button>
                </p>
            </div>
        </section>
    </div>

</div>
<!-- end: page -->

GT.Application/Views/Shared/_InfoUser.cshtml
<div id="userbox" class="userbox">
    <a href="#" data-toggle="dropdown">
        <figure class="profile-picture">
            <img src="~/Content/images/!logged-user.jpg" alt="Christian Castellanos" class="img-circle" data-lock-picture="~/Content/images/!logged-user.jpg" />
        </figure>
        <div class="profile-info" data-lock-name="Christian" data-lock-email="cdcastellanos@elektra.com.mx">
            <span class="name">Christian Castellanos</span>
            <span class="role">administrador</span>
        </div>

        <i class="fa custom-caret"></i>
    </a>

    <div class="dropdown-menu">
        <ul class="list-unstyled">
            <li class="divider"></li>
            <li>
                <a role="menuitem" tabindex="-1" href="pages-user-profile.html"><i class="fa fa-user"></i> Perfil</a>
            </li>
            <li>
                <a role="menuitem" tabindex="-1" href="pages-signin.html"><i class="fa fa-power-off"></i> Salir</a>
            </li>
        </ul>
    </div>
</div>

GT.Application/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html class="fixed">
<head>

    <!-- Basic -->
    <meta charset="UTF-8">

    <title>Wiki Sistemas Riesgos</title>
    <meta name="keywords" content="Glosario" />
    <meta name="description" content="Wiki Sistemas Riesgos">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <!-- Web Fonts  -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">

    <!-- Vendor CSS -->
    @Styles.Render("~/Content/bootstrap/css")
    <!-- Plugins CSS -->
    @Styles.Render("~/Content/plugins/css")
    <!-- Theme CSS -->
    @Styles.Render("~/Content/theme/css")

    @RenderSection("styles", required: false)
    <!-- Head Libs -->
    @Scripts.Render("~/bundles/modernizr")


    <script>
        var baseUrl = function (url) {
            return '@Href("~/")'+url;
        }
    </script>
</head>
<body>
    <section class="body">

        <!-- start: header -->
        <header class="header">
            <div class="logo-container">
                <a href="../" class="logo">
                    <img src="~/Content/images/logo_wiki.png" height="35" alt="Wiki Sistemas Riesgos" />
                </a>
                <div class="visible-xs toggle-sidebar-left" data-toggle-class="sidebar-left-opened" data-target="html" data-fire-event="sidebar-left-opened">
                    <i class="fa fa-bars" aria-label="Toggle sidebar"></i>
                </div>
            </div>

            <!-- start: search & user box -->
            <div class="header-right">

                <span class="separator"></span>

                @Html.Partial("_InfoUser")
            </div>
            <!-- end: search & user box -->
        </header>
        <!-- end: header -->

        <div class="inner-wrapper">
            <!-- start: sidebar -->
            @Html.Partial("_MenuPrincipal")
            <!-- end: sidebar -->

            <section role="main" class="content-body">
                <header class="page-header">
                    @RenderSection("title", required: true)
                    @RenderSection("breadcrumb", required: false)
                </header>

                <!-- start: page -->
                @RenderBody()
                <!-- end: page -->
            </section>
        </div>

    </section>

    <!-- Vendor -->
    @Scripts.Render("~/bundles/vendor")
    <!-- Plugins -->
    @Scripts.Render("~/bundles/plugins")

    <!-- VueJS -->
    @Scripts.Render("~/bundles/vue")

    @RenderSection("scripts", required: false)
    <!-- Theme Base, Components and Settings -->
    @Scripts.Render("~/bundles/theme")
</body>
</html>

GT.Application/Views/Shared/_MenuPrincipal.cshtml
<aside id="sidebar-left" class="sidebar-left">

    <div class="sidebar-header">
        <div class="sidebar-title" style="color:whitesmoke">
            MENÚ
        </div>
        <div class="sidebar-toggle hidden-xs" data-toggle-class="sidebar-left-collapsed" data-target="html" data-fire-event="sidebar-left-toggle">
            <i class="fa fa-bars" aria-label="Toggle sidebar"></i>
        </div>
    </div>

    <div class="nano">
        <div class="nano-content">
            <nav id="menu" class="nav-main" role="navigation">
                <ul class="nav nav-main">
                    <li>
                        <a href="@Url.Action("Index", "Home")">
                            <i class="fa fa-home" aria-hidden="true"></i>
                            <span>Index</span>
                        </a>
                    </li>
                    <li class="nav-parent nav-expanded ">
                        <a>
                            <i class="fa fa-gear" aria-hidden="true"></i>
                            <span>Catalogos</span>
                        </a>
                        <ul class="nav nav-children">
                            <li>
                                <a href='@Url.Action("Index", "Categoria")'>
                                    Categoría
                                </a>
                            </li>
                            <li>
                                <a href='@Url.Action("Index", "Concepto")'>
                                    Concepto
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>

    </div>

</aside>